/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bytatech.ayoos.doctor.apigateway.client.doctor.api;

import com.bytatech.ayoos.doctor.apigateway.client.doctor.model.ScheduleDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2018-08-06T12:17:49.149+05:30[Asia/Kolkata]")

@Api(value = "ScheduleResource", description = "the ScheduleResource API")
public interface ScheduleResourceApi {

    @ApiOperation(value = "createSchedule", nickname = "createScheduleUsingPOST", notes = "", response = ScheduleDTO.class, tags={ "schedule-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ScheduleDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/schedules",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<ScheduleDTO> createScheduleUsingPOST(@ApiParam(value = "scheduleDTO" ,required=true )  @Valid @RequestBody ScheduleDTO scheduleDTO);


    @ApiOperation(value = "deleteSchedule", nickname = "deleteScheduleUsingDELETE", notes = "", tags={ "schedule-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/schedules/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteScheduleUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllSchedules", nickname = "getAllSchedulesUsingGET", notes = "", response = ScheduleDTO.class, responseContainer = "List", tags={ "schedule-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ScheduleDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/schedules",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<ScheduleDTO>> getAllSchedulesUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getSchedule", nickname = "getScheduleUsingGET", notes = "", response = ScheduleDTO.class, tags={ "schedule-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ScheduleDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/schedules/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<ScheduleDTO> getScheduleUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchSchedules", nickname = "searchSchedulesUsingGET", notes = "", response = ScheduleDTO.class, responseContainer = "List", tags={ "schedule-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ScheduleDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/schedules",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<ScheduleDTO>> searchSchedulesUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateSchedule", nickname = "updateScheduleUsingPUT", notes = "", response = ScheduleDTO.class, tags={ "schedule-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = ScheduleDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/schedules",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<ScheduleDTO> updateScheduleUsingPUT(@ApiParam(value = "scheduleDTO" ,required=true )  @Valid @RequestBody ScheduleDTO scheduleDTO);

}
