/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.bytatech.ayoos.doctor.apigateway.client.doctor.api;

import com.bytatech.ayoos.doctor.apigateway.client.doctor.model.SessionDTO;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2018-08-06T12:17:49.149+05:30[Asia/Kolkata]")

@Api(value = "SessionResource", description = "the SessionResource API")
public interface SessionResourceApi {

    @ApiOperation(value = "createSession", nickname = "createSessionUsingPOST", notes = "", response = SessionDTO.class, tags={ "session-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = SessionDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/sessions",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<SessionDTO> createSessionUsingPOST(@ApiParam(value = "sessionDTO" ,required=true )  @Valid @RequestBody SessionDTO sessionDTO);


    @ApiOperation(value = "deleteSession", nickname = "deleteSessionUsingDELETE", notes = "", tags={ "session-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/sessions/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteSessionUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllSessions", nickname = "getAllSessionsUsingGET", notes = "", response = SessionDTO.class, responseContainer = "List", tags={ "session-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = SessionDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/sessions",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<SessionDTO>> getAllSessionsUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getSession", nickname = "getSessionUsingGET", notes = "", response = SessionDTO.class, tags={ "session-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = SessionDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/sessions/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<SessionDTO> getSessionUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchSessions", nickname = "searchSessionsUsingGET", notes = "", response = SessionDTO.class, responseContainer = "List", tags={ "session-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = SessionDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/sessions",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<SessionDTO>> searchSessionsUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateSession", nickname = "updateSessionUsingPUT", notes = "", response = SessionDTO.class, tags={ "session-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = SessionDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/sessions",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<SessionDTO> updateSessionUsingPUT(@ApiParam(value = "sessionDTO" ,required=true )  @Valid @RequestBody SessionDTO sessionDTO);

}
